<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="C:\Dev\erbai-livetool\src\Erbai.Live.Bilibili\Erbai.Live.Bilibili.csproj" />
    <ProjectReference Include="C:\Dev\erbai-livetool\src\Erbai.Modules.SongRequest\Erbai.Modules.SongRequest.csproj" />
  </ItemGroup>
</Project>
